package de.mas.wiiu.streaming.audio;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

/**
 * Checked against the same reference vector as the console's encoder
 * (plugin/tests/host/encoder_test.cpp), generated by an independent IMA ADPCM
 * implementation. If both pass, what the console encodes is what we decode.
 */
class ImaAdpcmTest {

    // One byte per stereo frame: left code in the low nibble, right in the high.
    static final int[] PACKED = { 0, 119, 119, 119, 119, 119, 119, 119, 126, 126, 123, 26, 8, 0, 3, 5, 4, 3, 130, 194,
            192, 200, 187, 204, 173, 139, 138, 10, 25, 81, 82, 53, 52, 3, 2, 130, 209, 201, 202, 157, 12, 11, 58, 90, 57,
            1, 130, 197, 196, 163, 130, 18, 81, 57, 10, 141, 204, 203, 138, 10, 57, 81, 2, 149 };

    static final int[] LEFT_DECODED = { 0, 11, 41, 104, 240, 533, 1164, 2521, -1, -4467, -8727, -11494, -11997,
            -11540, -8631, -4473, 508, 5195, 8238, 11005, 11508, 11051, 8142, 4740, -292, -4979, -8022, -10789, -12298,
            -10926, -8848, -4690, 291, 4978, 8021, 10788, 12297, 10925, 8847, 4689, -292, -4979, -8022, -10789, -12298,
            -10926, -8848, -4690, 291, 4978, 8021, 10788, 12297, 10925, 8847, 4689, -292, -4979, -8022, -10789, -12298,
            -10926, -8848, -4690 };

    static final int[] RIGHT_DECODED = { 0, 11, 41, 104, 240, 533, 1164, 2521, 5431, 11667, 25039, 30772, 32509,
            32767, 32767, 32767, 32767, 32767, 31787, 23764, 14056, 2309, -8745, -21667, -30353, -31932, -32768, -31463,
            -27904, -16039, 1333, 17520, 32235, 32767, 32767, 31188, 15395, -3525, -26418, -32768, -29970, -27427,
            -11240, 11884, 32767, 32767, 30224, 9412, -15771, -32699, -32768, -24374, 3606, 29675, 32767, 29690, 4507,
            -25964, -30059, -26335, -2636, 31219, 32767, 21595 };

    @Test
    void decodesTheReferenceVector() {
        final byte[] in = new byte[PACKED.length];
        for (int i = 0; i < in.length; i++) {
            in[i] = (byte) PACKED[i];
        }
        final ImaAdpcm.State left = new ImaAdpcm.State(0, 0);
        final ImaAdpcm.State right = new ImaAdpcm.State(0, 0);
        final byte[] pcm = new byte[in.length * 4];
        final int n = ImaAdpcm.decodeStereo(in, 0, in.length, left, right, pcm, 0);
        assertEquals(in.length * 4, n);

        final int[] l = new int[in.length];
        final int[] r = new int[in.length];
        for (int i = 0; i < in.length; i++) {
            l[i] = (short) ((pcm[i * 4] & 0xFF) | (pcm[i * 4 + 1] << 8));
            r[i] = (short) ((pcm[i * 4 + 2] & 0xFF) | (pcm[i * 4 + 3] << 8));
        }
        assertArrayEquals(LEFT_DECODED, l);
        assertArrayEquals(RIGHT_DECODED, r);

        // End state, also from the reference.
        assertEquals(-4690, left.predictor);
        assertEquals(67, left.index);
        assertEquals(21595, right.predictor);
        assertEquals(86, right.index);
    }

    @Test
    void decodingCanStartMidStreamFromAHeaderState() {
        // Each datagram carries the state it starts from; decoding from it must
        // give exactly what a decoder that saw everything before would.
        final byte[] in = new byte[PACKED.length];
        for (int i = 0; i < in.length; i++) {
            in[i] = (byte) PACKED[i];
        }
        final ImaAdpcm.State l = new ImaAdpcm.State(0, 0);
        final ImaAdpcm.State r = new ImaAdpcm.State(0, 0);
        final byte[] scratch = new byte[4 * 32];
        ImaAdpcm.decodeStereo(in, 0, 32, l, r, scratch, 0);

        final ImaAdpcm.State l2 = new ImaAdpcm.State(l.predictor, l.index);
        final ImaAdpcm.State r2 = new ImaAdpcm.State(r.predictor, r.index);
        final byte[] pcm = new byte[4 * 32];
        ImaAdpcm.decodeStereo(in, 32, 32, l2, r2, pcm, 0);
        assertEquals((short) LEFT_DECODED[32], (short) ((pcm[0] & 0xFF) | (pcm[1] << 8)));
        assertEquals((short) RIGHT_DECODED[63], (short) ((pcm[31 * 4 + 2] & 0xFF) | (pcm[31 * 4 + 3] << 8)));
    }
}
